<a href="https://colab.research.google.com/github/yongjaeahn/UwpQuickStart/blob/master/korean/source/06_02_%EC%88%98%ED%95%99_%EC%8A%A4%EC%B9%BC%EB%9D%BC%2C_%EB%B2%A1%ED%84%B0%2C_%ED%96%89%EB%A0%AC_%EA%B7%B8%EB%A6%AC%EA%B3%A0_%ED%85%90%EC%84%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

	스칼라, 벡터, 행렬 그리고 텐서

스칼라

In [ ]:
def add_two_numbers(number1, number2):
  sum = number1 + number2
  return sum

print(add_two_numbers(10,20))

30


In [ ]:
print(add_two_numbers(number2=20,number1=10))

30


In [ ]:
print(add_two_numbers(10,number2=20))

30


In [ ]:
def add_numbers(*numbers):   # 가변 위치 인자 정의
  sum = 0
  for number in numbers:
    print("number :", number)
    sum = sum + number
  return sum

print(add_numbers())         # 가변 위치 인자 바인딩
print(add_numbers(10))
print(add_numbers(10,20))
print(add_numbers(10,20,30))

0
number : 10
10
number : 10
number : 20
30
number : 10
number : 20
number : 30
60


In [ ]:
def add_numbers(*numbers,start=0):   # start 인자의 초기값 지정
  sum = start
  for number in numbers:
    #print("number :", number)
    sum = sum + number
  return sum

print(add_numbers(10,20))            # start 인자의 초기값 사용
print(add_numbers(10,20,start=100))  # start 인자의 값 별도 지정

30
130


In [ ]:
def list_keyword_args(**kwargs):  # 가변 키워드 인자 정의
  print('list_keyword_args() 함수 시작')
  for key, value in kwargs.items():
    print(key, '=',value)

list_keyword_args()               # 가변 키워드 인자 바인딩
list_keyword_args(name="홍길동")
list_keyword_args(name="홍길동", age=25)
list_keyword_args(name="홍길동", age=25, address="율도국")

list_keyword_args() 함수 시작
list_keyword_args() 함수 시작
name = 홍길동
list_keyword_args() 함수 시작
name = 홍길동
age = 25
list_keyword_args() 함수 시작
name = 홍길동
age = 25
address = 율도국


In [ ]:
print(add_two_numbers(number2=20,10))

SyntaxError: ignored

In [ ]:
print("Python 연산자")
print("2의 세제곱 : ", 2**3)
print("2.0의 세제곱 : ", 2.0**3)
print("1+2j의 세제곱 : ", (1+2j)**3)
print("2의 제곱근 : ", 2**0.5)
print()

print("Python 내장 수학 함수")
print("-3의 절대값 : ", abs(-3))
print("-3.5의 절대값 : ", abs(-3.5))
print("1+2j의 절대값 : ", abs(1+2j))
print("2의 세제곱 : ", pow(2,3))
print("2.0의 세제곱 : ", pow(2.,3))
print("리스트의 합 : ", sum([.1, .1, .1, .1, .1, .1, .1, .1, .1, .1]))
print()

import math
print("math 모듈 수학 함수")
print("-3의 절대값 : ", math.fabs(-3))
print("-3.5의 절대값 : ", math.fabs(-3.5))
#print("1+2j의 절대값 : ", math.fabs(1+2j))     # 오류가 발생하여 주석 처리
print("2의 세제곱 : ", math.pow(2,3))
print("리스트의 합 : ", math.fsum([.1, .1, .1, .1, .1, .1, .1, .1, .1, .1]))
print("2의 제곱근 : ", math.sqrt(2))

Python 연산자
2의 세제곱 :  8
2.0의 세제곱 :  8.0
1+2j의 세제곱 :  (-11-2j)
2의 제곱근 :  1.4142135623730951

Python 내장 수학 함수
-3의 절대값 :  3
-3.5의 절대값 :  3.5
1+2j의 절대값 :  2.23606797749979
2의 세제곱 :  8
2.0의 세제곱 :  8.0
리스트의 합 :  0.9999999999999999

math 모듈 수학 함수
-3의 절대값 :  3.0
-3.5의 절대값 :  3.5
2의 세제곱 :  8.0
리스트의 합 :  1.0
2의 제곱근 :  1.4142135623730951


벡터

In [ ]:
list_vector1 = [1,2,3,4,5]
list_vector2 = [5,4,3,2,1]
print("벡터의 덧셈 : ",list_vector1 + list_vector2)
print("벡터의 뺄셈 : ",list_vector1 - list_vector2)

벡터의 덧셈 :  [1, 2, 3, 4, 5, 5, 4, 3, 2, 1]


TypeError: ignored

In [ ]:
import numpy as np
array_vector1 = np.array([1,2,3,4,5])
array_vector2 = np.array([5,4,3,2,1])
print("벡터의 덧셈 : ",array_vector1 + array_vector2)
print("벡터의 뺄셈 : ",array_vector1 - array_vector2)
print("벡터의 곱셈 : ",array_vector1 * array_vector2)
print("벡터의 나눗셈 : ",array_vector1 / array_vector2)
print("벡터의 자승 : ",array_vector1 ** array_vector2)

벡터의 덧셈 :  [6 6 6 6 6]
벡터의 뺄셈 :  [-4 -2  0  2  4]
벡터의 곱셈 :  [5 8 9 8 5]
벡터의 나눗셈 :  [0.2 0.5 1.  2.  5. ]
벡터의 자승 :  [ 1 16 27 16  5]


In [ ]:
import numpy as np
array_vector = np.array([1,2,3,4,5])
print("벡터와 스칼라의 덧셈 : ", array_vector + 2)
print("벡터와 스칼라의 뺄셈 : ", array_vector - 2)
print("벡터와 스칼라의 곱셈 : ", array_vector * 2)
print("벡터와 스칼라의 나눗셈 : ", array_vector / 2)
print("벡터와 스칼라의 자승 : ", array_vector ** 2)
print()
print("스칼라와 벡터의 덧셈 : ", 2 + array_vector)
print("스칼라와 벡터의 뺄셈 : ", 2 - array_vector)
print("스칼라와 벡터의 곱셈 : ", 2 * array_vector)
print("스칼라와 벡터의 나눗셈 : ", 2 / array_vector)
print("스칼라와 벡터의 자승 : ", 2 ** array_vector)

벡터와 스칼라의 덧셈 :  [3 4 5 6 7]
벡터와 스칼라의 뺄셈 :  [-1  0  1  2  3]
벡터와 스칼라의 곱셈 :  [ 2  4  6  8 10]
벡터와 스칼라의 나눗셈 :  [0.5 1.  1.5 2.  2.5]
벡터와 스칼라의 자승 :  [ 1  4  9 16 25]

스칼라와 벡터의 덧셈 :  [3 4 5 6 7]
스칼라와 벡터의 뺄셈 :  [ 1  0 -1 -2 -3]
스칼라와 벡터의 곱셈 :  [ 2  4  6  8 10]
스칼라와 벡터의 나눗셈 :  [2.         1.         0.66666667 0.5        0.4       ]
스칼라와 벡터의 자승 :  [ 2  4  8 16 32]


In [ ]:
list_vector = [1,-2,3,-4,5]
abs(list_vector)

TypeError: ignored

In [ ]:
list_vector = [1,-2,3,-4,5]

for scala in list_vector:
  print("abs("+str(scala)+") = ", abs(scala))

abs(1) =  1
abs(-2) =  2
abs(3) =  3
abs(-4) =  4
abs(5) =  5


In [ ]:
import numpy as np
array_vector = np.array([1,-2,3,-4,5])
abs(array_vector)

array([1, 2, 3, 4, 5])

In [ ]:
import numpy as np
array_vector = np.array([1,-2,3,-4,5])

for scala in array_vector:
  print("abs("+str(scala)+") = ", abs(scala))

abs(1) =  1
abs(-2) =  2
abs(3) =  3
abs(-4) =  4
abs(5) =  5


In [ ]:
import numpy as np
import math

#list_vector = [1,-2,3,-4,5]           # 오류가 발생하여 주석 처리
#print(math.fabs(list_vector))         # 오류가 발생하여 주석 처리

array_vector = np.array([1,-2,3,-4,5])
print(math.fabs(array_vector))

TypeError: ignored

In [ ]:
import numpy as np

array_vector = np.array([1,-2,3,-4,5])
print(np.abs(array_vector))

[1 2 3 4 5]


행렬

In [ ]:
list_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(list_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
import numpy as np
array_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
array_tensor3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                           [[10,11,12],[13,14,15],[16,17,18]],
                           [[10,20,21],[22,23,24],[25,26,27]]])
print(array_tensor3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[10 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
import numpy as np

array1d = np.arange(1,10)
print(array1d)

array2d = np.arange(1,10).reshape(3,3)
print(array_matrix)

array3d = np.arange(1,28).reshape(3,3,3)
print(array3d)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
import numpy as np

array1d = np.arange(1,10).reshape(3,3).reshape(9)
print(array1d)

array3d = np.arange(1,28).reshape(3,3,3)
print(array3d)
print(array3d.reshape(-1))

[1 2 3 4 5 6 7 8 9]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [ ]:
import numpy as np

array2d = np.arange(1,10).reshape(3,3)
print('array2d\n',array2d)

print('1차원-reshape() 메소드',array2d.reshape(-1))
print('1차원-revel() 메소드',array2d.ravel())
print('1차원-flat 속성',array2d.flat)
for element in array2d.flat:
  print(element,end=' ')

array2d
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1차원-reshape() 메소드 [1 2 3 4 5 6 7 8 9]
1차원-revel() 메소드 [1 2 3 4 5 6 7 8 9]
1차원-flat 속성 <numpy.flatiter object at 0x564506f74a40>
1 2 3 4 5 6 7 8 9 

In [ ]:
import numpy as np

list4d = [[[['R111','G111','B111'],['R112','G112','B112']],
           [['R121','G121','B121'],['R122','G122','B122']]],

          [[['R211','G211','B211'],['R212','G212','B212']],
           [['R221','G221','B221'],['R222','G222','B222']]]]

array4d = np.array(list4d)
print('array4d의 형상:',array4d.shape)

array4d의 형상: (2, 2, 2, 3)


In [ ]:
array2d = array4d.reshape(2,12)
print('array2d\n',array2d)

array2d
 [['R111' 'G111' 'B111' 'R112' 'G112' 'B112' 'R121' 'G121' 'B121' 'R122'
  'G122' 'B122']
 ['R211' 'G211' 'B211' 'R212' 'G212' 'B212' 'R221' 'G221' 'B221' 'R222'
  'G222' 'B222']]


In [ ]:
array2d = array4d.reshape(2,-1)
print('array2d\n',array2d)

array2d
 [['R111' 'G111' 'B111' 'R112' 'G112' 'B112' 'R121' 'G121' 'B121' 'R122'
  'G122' 'B122']
 ['R211' 'G211' 'B211' 'R212' 'G212' 'B212' 'R221' 'G221' 'B221' 'R222'
  'G222' 'B222']]


In [ ]:
import numpy as np

print(np.random.rand(2,3))                # 1을 포함하지 않는 0~1사이의 실수 난수
print(np.random.randint(6,size=(2,3)))    # 0~5사이의 정수 난수
print(np.random.randint(1,7,size=(2,3)))  # 1~6사이의 정수 난수
print(np.random.randn(2,3))               # 정규분포(평균 0, 표준편자 1) 실수 난수

[[0.5745447  0.55074943 0.9991471 ]
 [0.81930482 0.33285708 0.41793689]]
[[5 2 2]
 [0 2 3]]
[[6 3 6]
 [1 2 1]]
[[-0.73245638 -0.28201239  1.37501889]
 [-0.94309531 -0.21941694 -0.62192199]]


In [ ]:
import random
import numpy as np

for _ in range(20):
  print(random.randrange(1,7),end=' ')
print()
for _ in range(20):
  print(np.random.randint(1,7),end=' ')

5 1 5 1 2 3 5 2 3 1 6 5 6 1 4 5 3 4 1 2 
3 5 5 5 3 2 3 6 4 3 1 4 1 1 2 4 1 6 4 2 

In [ ]:
print(random.randrange(1,7,2))            # 홀수 난수
print(random.randrange(2,7,2))            # 짝수 난수
print(np.random.randint(1,7,(2,3)))       # 2 X 3 행렬 난수
print(np.random.randint(1,7,size=(2,2)))  # 2 X 2 행렬 난수

3
2
[[6 2 1]
 [6 5 5]]
[[4 5]
 [3 1]]


In [ ]:
print(random.random())        # 1을 포함하지 않는 0~1사이의 실수 난수
print(np.random.rand())       # 1을 포함하지 않는 0~1사이의 실수 난수
print(np.random.rand(2,3))    # 1을 포함하지 않는 0~1사이의 실수 난수 (2 X 3 배열)

0.5081139706913528
0.3021189758113202
[[0.19033745 0.93991803 0.71004323]
 [0.65664406 0.85566369 0.06733242]]


In [ ]:
for _ in range(5):
  print(random.uniform(5,10),end=' ')   # 10을 포함하지 않는 5~10사이의 실수 난수
print()
for _ in range(5):
  print(5+random.random()*5,end=' ')    # 10을 포함하지 않는 5~10사이의 실수 난수
print()
for _ in range(5):
  print(5+np.random.rand()*5,end=' ')   # 10을 포함하지 않는 5~10사이의 실수 난수

5.873825578410558 8.246097794989007 7.351412435455403 6.944546912041011 6.300053051146852 
5.153590191862248 8.749435658950635 6.4213044954353204 7.479888277273383 7.573006362049832 
7.97455337185401 9.786406918448337 7.46870576827795 6.957089900993886 5.649770196652527 

In [ ]:
# 하나의 난수
print(np.random.randn())                  # 정규분포(평균 0, 표준편자 1) 실수 난수
print(np.random.normal(90,10))            # 정규분포(평균 90, 표준편자 10) 실수 난수
# 길이가 5인 벡터
print(np.random.randn(5))                 # 정규분포(평균 0, 표준편자 1) 실수 난수
print(np.random.normal(90,10,size=5))     # 정규분포(평균 90, 표준편자 10) 실수 난수
# 2X3 배열
print(np.random.randn(2,3))               # 정규분포(평균 0, 표준편자 1) 실수 난수
print(np.random.normal(90,10,size=(2,3))) # 정규분포(평균 90, 표준편자 10) 실수 난수

0.6597870858335965
103.56408831174102
[ 1.49772671 -0.3393504  -0.43236208  1.14342066 -0.69243313]
[68.81885619 73.34441971 95.45176389 94.69085933 87.69411168]
[[ 0.32585796 -1.38560498  0.33753711]
 [ 0.5015135  -0.83120397 -0.20219147]]
[[ 82.99569654 102.02835877  83.25308744]
 [ 83.86473348  83.83988809  95.25141292]]


In [ ]:
for _ in range(5):
  print(random.randrange(1,11),end=' ')
print()
for _ in range(5):
  print(np.random.randint(1,11),end=' ')

3 3 7 4 8 
10 2 2 1 9 

In [ ]:
for _ in range(5):
  print(random.randrange(1,11),end=' ')
print()
for _ in range(5):
  print(np.random.randint(1,11),end=' ')

3 8 6 3 3 
4 10 2 6 3 

In [ ]:
random.seed(1234)
for _ in range(5):
  print(random.randrange(1,11),end=' ')
print()
np.random.seed(1234)
for _ in range(5):
  print(np.random.randint(1,11),end=' ')

8 2 1 2 10 
4 7 6 5 9 

In [ ]:
random.seed(1234)
for _ in range(5):
  print(random.randrange(1,11),end=' ')
print()
np.random.seed(1234)
for _ in range(5):
  print(np.random.randint(1,11),end=' ')

8 2 1 2 10 
4 7 6 5 9 

In [ ]:
import numpy as np

array_matrix = np.arange(1,10).reshape(3,3)
print("행렬 : \n", array_matrix)

print("행렬 덧셈 : \n", array_matrix + array_matrix)
print("행렬 나눗셈 : \n", array_matrix / array_matrix)

행렬 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
행렬 덧셈 : 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
행렬 나눗셈 : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

array_matrix = np.arange(9).reshape(3,3)
print("행렬 : \n", array_matrix)

print("행렬의 배열 곱셈 : \n", array_matrix * array_matrix)
print("행렬의 행렬 곱셈 : \n", array_matrix @ array_matrix)

행렬 : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
행렬의 배열 곱셈 : 
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
행렬의 행렬 곱셈 : 
 [[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [ ]:
import numpy as np

array_matrix = np.arange(9).reshape(3,3)
print("행렬 : \n", array_matrix)

print("행렬과 스칼라 곱셈 : \n", array_matrix * 2)
print("행렬 제곱근 : \n", np.sqrt(array_matrix))

행렬 : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
행렬과 스칼라 곱셈 : 
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
행렬 제곱근 : 
 [[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


In [ ]:
result = 0 / 0

ZeroDivisionError: ignored

In [ ]:
import numpy as np

array_matrix01 = np.array([[-2,-1,0,1,2],[1,2,3,4,5]])
print("나누어지는 행렬 : \n", array_matrix01)
array_matrix02 = np.array([[1,0,0,0,1],[5,4,3,2,1]])
print("나누는 행렬 : \n", array_matrix02)
array_matrix03 = array_matrix01 / array_matrix02
print("나누어진 행렬 : \n", array_matrix03)

나누어지는 행렬 : 
 [[-2 -1  0  1  2]
 [ 1  2  3  4  5]]
나누는 행렬 : 
 [[1 0 0 0 1]
 [5 4 3 2 1]]
나누어진 행렬 : 
 [[-2.  -inf  nan  inf  2. ]
 [ 0.2  0.5  1.   2.   5. ]]


<ipython-input-33-10d794c47070>:7: RuntimeWarning: divide by zero encountered in true_divide
  array_matrix03 = array_matrix01 / array_matrix02
<ipython-input-33-10d794c47070>:7: RuntimeWarning: invalid value encountered in true_divide
  array_matrix03 = array_matrix01 / array_matrix02


In [ ]:
print("np.sqrt(-1) : ", np.sqrt(-1))
print("np.sqrt(np.inf) : ", np.sqrt(np.inf))
print("np.log(0) : ", np.log(0))
print("np.exp(-np.inf) : ", np.exp(-np.inf))

np.sqrt(-1) :  nan
np.sqrt(np.inf) :  inf
np.log(0) :  -inf
np.exp(-np.inf) :  0.0


<ipython-input-34-943bd00e8266>:1: RuntimeWarning: invalid value encountered in sqrt
  print("np.sqrt(-1) : ", np.sqrt(-1))
<ipython-input-34-943bd00e8266>:3: RuntimeWarning: divide by zero encountered in log
  print("np.log(0) : ", np.log(0))


In [ ]:
import math

print("math.sqrt(-1) :", math.sqrt(-1))

ValueError: ignored

In [12]:
coupon = None

if coupon is not None:
  print("여기에 쿠폰 처리 로직을 기술합니다.")
else:
  print("여기에 쿠폰이 발급되지 않은 경우의 로직을 기술합니다.")

여기에 쿠폰이 발급되지 않은 경우의 로직을 기술합니다.


In [13]:
coupon = None

if coupon != None:
  print("여기에 쿠폰 처리 로직을 기술합니다.")
else:
  print("여기에 쿠폰이 발급되지 않은 경우의 로직을 기술합니다.")

여기에 쿠폰이 발급되지 않은 경우의 로직을 기술합니다.


In [14]:
coupon = None

if coupon:
  print("여기에 쿠폰 처리 로직을 기술합니다.")
else:
  print("여기에 쿠폰이 발급되지 않은 경우의 로직을 기술합니다.")

여기에 쿠폰이 발급되지 않은 경우의 로직을 기술합니다.


In [10]:
product_list = []

if product_list:
  print("여기에 제품 처리 로직을 기술합니다.")
else:
  print("여기에 제품이 없을 경우의 로직을 기술합니다.")

여기에 제품이 없을 경우의 로직을 기술합니다.


In [15]:
number = 0

if number is 0:
  print("여기에 숫자가 0일때의 처리 로직을 기술합니다.")
else:
  print("여기에 숫자가 0이 아닐 경우의 로직을 기술합니다.")

여기에 숫자가 0일때의 처리 로직을 기술합니다.


<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-15-5841845ef4ab>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if number is 0:


In [16]:
number = 0

if number == 0:
  print("여기에 숫자가 0일때의 처리 로직을 기술합니다.")
else:
  print("여기에 숫자가 0이 아닐 경우의 로직을 기술합니다.")

여기에 숫자가 0일때의 처리 로직을 기술합니다.


In [18]:
number = 0

if number:
  print("여기에 숫자가 0일때의 처리 로직을 기술합니다.")
else:
  print("여기에 숫자가 0이 아닐 경우의 로직을 기술합니다.")

여기에 숫자가 0이 아닐 경우의 로직을 기술합니다.


In [ ]:
import numpy as np

array_matrix = np.arange(9).reshape(3,3)
print("행렬 : \n", array_matrix)

print("전치 행렬 (array_matrix.T) : \n", array_matrix.T)
print("전치 행렬 (np.transpose(array_matrix)) : \n", np.transpose(array_matrix))

행렬 : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
전치 행렬 (array_matrix.T) : 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
전치 행렬 (np.transpose(array_matrix)) : 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
